on:
  push:
    tags:
      - "v*.*.*"

jobs:
  bump-version-and-build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - run: "sed -i 's/^version = \"[^\"]*\"/version = \"${{ github.ref_name }}\"/' pyproject.toml"

      - run: "pip install build && python -m build"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "version-bumped-code"
          path: "."

  pull-request-for-bumped-version:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/download-artifact@v4"
        with:
          name: "version-bumped-code"
      - id: "cpr"
        uses: "peter-evans/create-pull-request@v7"
        with:
          commit-message: "Bump version to ${{ github.ref_name }}"
          base: "master"

  publish-github:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/download-artifact@v4"
        with:
          name: "version-bumped-code"

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

  publish-pypi:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/download-artifact@v4"
        with:
          name: "version-bumped-code"

      - uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}