on:
  push:
    tags:
      - "v*.*.*"

jobs:
  bump-version-and-build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - run: "sed -i 's/^version = \"[^\"]*\"/version = \"${{ github.ref_name }}\"/' pyproject.toml"

      - run: "pip install build && python -m build"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "version-bumped-code-and-build"
          path: "."

  pull-request-for-bumped-version:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/download-artifact@v5"
        with:
          name: "version-bumped-code-and-build"

      - id: "cpr"
        uses: "peter-evans/create-pull-request@v7"
        with:
          token: "${{ secrets.GH_PAT }}"
          base: "master"
          branch: "bump-version"
          title: "Bump version"
          commit-message: "Bump version to ${{ github.ref_name }}"
      - run: "gh pr merge '${{ steps.cpr.outputs.pull-request-number }}' --merge --auto --delete-branch"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

  publish-github:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/download-artifact@v5"
        with:
          name: "version-bumped-code-and-build"

      - uses: "softprops/action-gh-release@v2"
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

  publish-pypi:
    needs: "bump-version-and-build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v5"
        with:
          name: "version-bumped-code-and-build"

      - uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}